[_]
schema-version = "0.2"

[io.buildpacks]
builder = "docker.io/paketobuildpacks/builder-noble-java-tiny"
exclude = [
    ".devcontainer",
    ".flox"
]

[[io.buildpacks.build.env]]
name = "BP_JVM_VERSION"
value = "24"
