spec:
  template:
    spec:
      containers:
        - env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: db-appointments-app
                key: jdbc-uri
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-appointments-app
                key: username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-appointments-app
                key: password
