apiVersion: v1
kind: ConfigMap
metadata:
  name: appointments-init-sql
data:
  init.sql: |- 
    CREATE TABLE appointments(
    id VARCHAR PRIMARY KEY NOT NULL,
    patientId VARCHAR NOT NULL,
    category VARCHAR NOT NULL,
    appointmentDate TIMESTAMP NOT NULL DEFAULT CURRENT_DATE);