apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: appointments
build:
  artifacts:
    - image: ko.local/appointments
      ko:
        dependencies:
          paths:
          - "**/*.go"
          - go.mod
          - db
manifests:
  rawYaml:
  - config/db.yml
  - config/deployment.yml
  - config/service.yml
