version = 1

[install]
go.pkg-path = "go"
httpie.pkg-path = "httpie"
vscode-go-flake.flake = "github:thomasvitale/vscode-go-flake"

[vars]
FLOX_DISABLE_METRICS="true"

[options]
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
