apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments
spec:
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
      - name: appointments
        image: ko://github.com/salaboy/devex-on-k8s/chapter03/end/go/appointments
        env: 
        - name: POSTGRES_HOST
          value: postgresql.default.svc.cluster.local
        - name: POSTGRES_USERNAME
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: postgres-password    